[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
startCommand = "node dist/src/main.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
